appname: IdP
httpport: 3000
httpaddr: "127.0.0.1"


hydraAdmin: "http://localhost:4445"
hydraAPI: "http://localhost:4444"
clientId: "Hiveon-API"
clientSecret: "secret"
remember_for: 360000



postgres:
  host: "116.203.56.122"
  port: "5432"
  dbName: "oauth"
  user: 
  password: 

notification:
  active: "true"
  smtp: "smtp.gmail.com"
  port: "465"
  user: "hiveonid"
  password: "11_hiveonid"
  from: "HiveonId@support.com"
